import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

/**
 * Generate a multi-page sample PDF for testing.
 * Proves pdf-lib can create PDFs from scratch.
 */
export async function generateSamplePdf(): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  // Page 1: Title page
  const page1 = pdfDoc.addPage([612, 792])
  page1.drawText('ORMC AI Document Audit', {
    x: 120,
    y: 600,
    size: 28,
    font: boldFont,
    color: rgb(0.1, 0.15, 0.4),
  })
  page1.drawText('Sample Audit Document for Spike Testing', {
    x: 130,
    y: 560,
    size: 14,
    font,
    color: rgb(0.4, 0.4, 0.4),
  })
  page1.drawText('This PDF was generated by pdf-lib to test rendering and annotation capabilities.', {
    x: 50,
    y: 480,
    size: 11,
    font,
    color: rgb(0.2, 0.2, 0.2),
  })
  page1.drawText('Features being tested:', {
    x: 50,
    y: 440,
    size: 12,
    font: boldFont,
    color: rgb(0.2, 0.2, 0.2),
  })
  const features = [
    '1. PDF rendering in the browser via pdf.js / react-pdf',
    '2. Text layer rendering (selectable text)',
    '3. Annotation overlay (text highlights + comments)',
    '4. Shape drawing overlay (rectangles + circles)',
    '5. PDF export with annotations embedded via pdf-lib',
    '6. PDF merging with bookmarks via pdf-lib',
  ]
  features.forEach((f, i) => {
    page1.drawText(f, {
      x: 70,
      y: 410 - i * 22,
      size: 11,
      font,
      color: rgb(0.3, 0.3, 0.3),
    })
  })

  // Page 2: Safety audit content (simulating a real document)
  const page2 = pdfDoc.addPage([612, 792])
  page2.drawText('Section 1: Chemical Hazard Assessment', {
    x: 50,
    y: 720,
    size: 18,
    font: boldFont,
    color: rgb(0.1, 0.15, 0.4),
  })
  const content = [
    'The laboratory handles the following chemical categories:',
    '',
    '• Flammable liquids (ethanol, acetone, methanol)',
    '• Corrosive substances (hydrochloric acid, sodium hydroxide)',
    '• Toxic compounds (formaldehyde, benzene derivatives)',
    '• Oxidizers (hydrogen peroxide >30%, potassium permanganate)',
    '',
    'Risk Level Assessment:',
    '',
    'All personnel must complete the mandatory Chemical Safety Training (CST-200)',
    'before accessing laboratory facilities. Personal protective equipment including',
    'lab coats, safety goggles, and nitrile gloves are required at all times.',
    '',
    'The chemical inventory must be updated monthly using the EHS360 system.',
    'Any discrepancies between physical inventory and system records must be',
    'reported to the Department Safety Coordinator within 48 hours.',
    '',
    'Emergency procedures are posted at each laboratory entrance and reviewed',
    'annually during the safety refresher training session.',
  ]
  content.forEach((line, i) => {
    page2.drawText(line, {
      x: 50,
      y: 680 - i * 20,
      size: 11,
      font: line.startsWith('Risk') ? boldFont : font,
      color: rgb(0.2, 0.2, 0.2),
    })
  })

  // Page 3: Compliance findings
  const page3 = pdfDoc.addPage([612, 792])
  page3.drawText('Section 2: Compliance Findings', {
    x: 50,
    y: 720,
    size: 18,
    font: boldFont,
    color: rgb(0.1, 0.15, 0.4),
  })
  const findings = [
    'Finding F-001: Expired fire extinguisher in Lab 3-201 (Due: 2025-12)',
    'Finding F-002: Missing SDS for solvent mixture XR-42 in chemical store',
    'Finding F-003: Fume hood airflow below minimum threshold (face velocity <80 fpm)',
    'Finding F-004: Emergency shower not tested within past 30 days',
    'Finding F-005: Biosafety cabinet certification expired (BSC-2A, Room 4-110)',
  ]
  findings.forEach((f, i) => {
    page3.drawText(f, {
      x: 50,
      y: 680 - i * 28,
      size: 11,
      font,
      color: rgb(0.6, 0.1, 0.1),
    })
  })

  return pdfDoc.save()
}
